<div class="article-inner">
 <header>
  <div class="entry-meta beforetitle-meta">
  </div>
  <!-- .entry-meta -->
  <h1 class="entry-title singular-title" itemprop="headline">
   27.10 — std::move_if_noexcept
  </h1>
  <div class="entry-meta aftertitle-meta">
  </div>
  <!-- .entry-meta -->
 </header>
 <div class="entry-content" itemprop="articleBody">
  <p>
   (h/t to reader Koe for providing the first draft of this lesson!)
  </p>
  <p>
   In lesson
   <a href="https://www.learncpp.com/cpp-tutorial/stdmove/">
    22.4 -- std::move
   </a>
   , we covered
   <code>
    std::move
   </code>
   , which casts its lvalue argument to an rvalue so that we can invoke move semantics.  And in lesson
   <a href="https://www.learncpp.com/cpp-tutorial/exception-specifications-and-noexcept/">
    27.9 -- Exception specifications and noexcept
   </a>
   , we covered the
   <code>
    noexcept
   </code>
   exception specifier and operator.  This lesson builds on both concepts.
  </p>
  <p>
   We also covered the
   <code>
    strong exception guarantee
   </code>
   , which guarantees that if a function is interrupted by an exception, no memory will be leaked and the program state will not be changed.  In particular, all constructors should uphold the strong exception guarantee, so that the rest of the program won’t be left in an altered state if construction of an object fails.
  </p>
  <p class="cpp-section cpp-topline" style="clear: both">
   The move constructors exception problem
  </p>
  <p>
   Consider the case where we are copying some object, and the copy fails for some reason (e.g. the machine is out of memory).  In such a case, the object being copied is not harmed in any way, because the source object doesn’t need to be modified to create a copy.  We can discard the failed copy, and move on.  The
   <code>
    strong exception guarantee
   </code>
   is upheld.
  </p>
  <p>
   Now consider the case where we are instead moving an object.  A move operation transfers ownership of a given resource from the source to the destination object.  If the move operation is interrupted by an exception after the transfer of ownership occurs, then our source object will be left in a modified state.  This isn’t a problem if the source object is a temporary object and going to be discarded after the move anyway -- but for non-temporary objects, we’ve now damaged the source object.  To comply with the
   <code>
    strong exception guarantee
   </code>
   , we’d need to move the resource back to the source object, but if the move failed the first time, there’s no guarantee the move back will succeed either.
  </p>
  <p>
   How can we give move constructors the
   <code>
    strong exception guarantee
   </code>
   ? It is simple enough to avoid throwing exceptions in the body of a move constructor, but a move constructor may invoke other constructors that are
   <code>
    potentially throwing
   </code>
   . Take for example the move constructor for
   <code>
    std::pair
   </code>
   , which must try to move each subobject in the source pair into the new pair object.
  </p>
  <pre class="language-cpp line-numbers"><code class="language-cpp match-braces">// Example move constructor definition for std::pair
// Take in an 'old' pair, and then move construct the new pair's 'first' and 'second' subobjects from the 'old' ones
template &lt;typename T1, typename T2&gt;
pair&lt;T1,T2&gt;::pair(pair&amp;&amp; old)
  : first(std::move(old.first)),
    second(std::move(old.second))
{}</code></pre>
  <p>
   Now lets use two classes,
   <code>
    MoveClass
   </code>
   and
   <code>
    CopyClass
   </code>
   , which we will
   <code>
    pair
   </code>
   together to demonstrate the
   <code>
    strong exception guarantee
   </code>
   problem with move constructors:
  </p>
  <pre class="language-cpp line-numbers"><code class="language-cpp match-braces">#include &lt;iostream&gt;
#include &lt;utility&gt; // For std::pair, std::make_pair, std::move, std::move_if_noexcept
#include &lt;stdexcept&gt; // std::runtime_error

class MoveClass
{
private:
  int* m_resource{};

public:
  MoveClass() = default;

  MoveClass(int resource)
    : m_resource{ new int{ resource } }
  {}

  // Copy constructor
  MoveClass(const MoveClass&amp; that)
  {
    // deep copy
    if (that.m_resource != nullptr)
    {
      m_resource = new int{ *that.m_resource };
    }
  }

  // Move constructor
  MoveClass(MoveClass&amp;&amp; that) noexcept
    : m_resource{ that.m_resource }
  {
    that.m_resource = nullptr;
  }

  ~MoveClass()
  {
    std::cout &lt;&lt; "destroying " &lt;&lt; *this &lt;&lt; '\n';

    delete m_resource;
  }

  friend std::ostream&amp; operator&lt;&lt;(std::ostream&amp; out, const MoveClass&amp; moveClass)
  {
    out &lt;&lt; "MoveClass(";

    if (moveClass.m_resource == nullptr)
    {
      out &lt;&lt; "empty";
    }
    else
    {
      out &lt;&lt; *moveClass.m_resource;
    }

    out &lt;&lt; ')';
    
    return out;
  }
};


class CopyClass
{
public:
  bool m_throw{};

  CopyClass() = default;

  // Copy constructor throws an exception when copying from
  // a CopyClass object where its m_throw is 'true'
  CopyClass(const CopyClass&amp; that)
    : m_throw{ that.m_throw }
  {
    if (m_throw)
    {
      throw std::runtime_error{ "abort!" };
    }
  }
};

int main()
{
  // We can make a std::pair without any problems:
  std::pair my_pair{ MoveClass{ 13 }, CopyClass{} };

  std::cout &lt;&lt; "my_pair.first: " &lt;&lt; my_pair.first &lt;&lt; '\n';

  // But the problem arises when we try to move that pair into another pair.
  try
  {
    my_pair.second.m_throw = true; // To trigger copy constructor exception

    // The following line will throw an exception
    std::pair moved_pair{ std::move(my_pair) }; // We'll comment out this line later
    // std::pair moved_pair{ std::move_if_noexcept(my_pair) }; // We'll uncomment this later

    std::cout &lt;&lt; "moved pair exists\n"; // Never prints
  }
  catch (const std::exception&amp; ex)
  {
      std::cerr &lt;&lt; "Error found: " &lt;&lt; ex.what() &lt;&lt; '\n';
  }

  std::cout &lt;&lt; "my_pair.first: " &lt;&lt; my_pair.first &lt;&lt; '\n';

  return 0;
}</code></pre>
  <p>
   The above program prints:
  </p>
  <pre>destroying MoveClass(empty)
my_pair.first: MoveClass(13)
destroying MoveClass(13)
Error found: abort!
my_pair.first: MoveClass(empty)
destroying MoveClass(empty)
</pre>
  <p>
   Let’s explore what happened. The first printed line shows the temporary
   <code>
    MoveClass
   </code>
   object used to initialize
   <code>
    my_pair
   </code>
   gets destroyed as soon as the
   <code>
    my_pair
   </code>
   instantiation statement has been executed. It is
   <code>
    empty
   </code>
   since the
   <code>
    MoveClass
   </code>
   subobject in
   <code>
    my_pair
   </code>
   was move constructed from it, demonstrated by the next line which shows
   <code>
    my_pair.first
   </code>
   contains the
   <code>
    MoveClass
   </code>
   object with value
   <code>
    13
   </code>
   .
  </p>
  <p>
   It gets interesting in the third line. We created
   <code>
    moved_pair
   </code>
   by copy constructing its
   <code>
    CopyClass
   </code>
   subobject (it doesn’t have a move constructor), but that copy construction threw an exception since we changed the Boolean flag. Construction of
   <code>
    moved_pair
   </code>
   was aborted by the exception, and its already-constructed members were destroyed. In this case, the
   <code>
    MoveClass
   </code>
   member was destroyed, printing
   <code>
    destroying MoveClass(13) variable
   </code>
   . Next we see the
   <code>
    Error found: abort!
   </code>
   message printed by
   <code>
    main()
   </code>
   .
  </p>
  <p>
   When we try to print
   <code>
    my_pair.first
   </code>
   again, it shows the
   <code>
    MoveClass
   </code>
   member is empty. Since
   <code>
    moved_pair
   </code>
   was initialized with
   <code>
    std::move
   </code>
   , the
   <code>
    MoveClass
   </code>
   member (which has a move constructor) got move constructed and
   <code>
    my_pair.first
   </code>
   was nulled.
  </p>
  <p>
   Finally,
   <code>
    my_pair
   </code>
   was destroyed at the end of main().
  </p>
  <p>
   To summarize the above results: the move constructor of
   <code>
    std::pair
   </code>
   used the throwing copy constructor of
   <code>
    CopyClass
   </code>
   .  This copy constructor threw an exception, causing the creation of
   <code>
    moved_pair
   </code>
   to abort, and
   <code>
    my_pair.first
   </code>
   to be permanently damaged.  The
   <code>
    strong exception guarantee
   </code>
   was not preserved.
  </p>
  <p class="cpp-section cpp-topline" style="clear: both">
   std::move_if_noexcept to the rescue
  </p>
  <p>
   Note that the above problem could have been avoided if
   <code>
    std::pair
   </code>
   had tried to do a copy instead of a move.  In that case,
   <code>
    moved_pair
   </code>
   would have failed to construct, but
   <code>
    my_pair
   </code>
   would not have been altered.
  </p>
  <p>
   But copying instead of moving has a performance cost that we don’t want to pay for all objects -- ideally we want to do a move if we can do so safely, and a copy otherwise.
  </p>
  <p>
   Fortunately, C++ has two mechanisms that, when used in combination, let us do exactly that.  First, because
   <code>
    noexcept
   </code>
   functions are no-throw/no-fail, they implicitly meet the criteria for the
   <code>
    strong exception guarantee
   </code>
   .  Thus, a
   <code>
    noexcept
   </code>
   move constructor is guaranteed to succeed.
  </p>
  <p>
   Second, we can use the standard library function
   <code>
    std::move_if_noexcept()
   </code>
   to determine whether a move or a copy should be performed.
   <code>
    std::move_if_noexcept
   </code>
   is a counterpart to
   <code>
    std::move
   </code>
   , and is used in the same way.
  </p>
  <p>
   If the compiler can tell that an object passed as an argument to
   <code>
    std::move_if_noexcept
   </code>
   won’t throw an exception when it is move constructed (or if the object is move-only and has no copy constructor), then
   <code>
    std::move_if_noexcept
   </code>
   will perform identically to
   <code>
    std::move()
   </code>
   (and return the object converted to an r-value).  Otherwise,
   <code>
    std::move_if_noexcept
   </code>
   will return a normal l-value reference to the object.
  </p>
  <div class="cpp-note cpp-lightbluebackground">
   <p class="cpp-note-title cpp-bottomline">
    Key insight
   </p>
   <p>
    <code>
     std::move_if_noexcept
    </code>
    will return a movable r-value if the object has a noexcept move constructor, otherwise it will return a copyable l-value.  We can use the
    <code>
     noexcept
    </code>
    specifier in conjunction with
    <code>
     std::move_if_noexcept
    </code>
    to use move semantics only when a strong exception guarantee exists (and use copy semantics otherwise).
   </p>
  </div>
  <p>
   Let’s update the code in the previous example as follows:
  </p>
  <pre class="language-cpp line-numbers"><code class="language-cpp match-braces">//std::pair moved_pair{std::move(my_pair)}; // comment out this line now
std::pair moved_pair{std::move_if_noexcept(my_pair)}; // and uncomment this line</code></pre>
  <p>
   Running the program again prints:
  </p>
  <pre>destroying MoveClass(empty)
my_pair.first: MoveClass(13)
destroying MoveClass(13)
Error found: abort!
my_pair.first: MoveClass(13)
destroying MoveClass(13)
</pre>
  <p>
   As you can see, after the exception was thrown, the subobject
   <code>
    my_pair.first
   </code>
   still points to the value
   <code>
    13
   </code>
   .
  </p>
  <p>
   The move constructor of
   <code>
    std::pair
   </code>
   isn’t
   <code>
    noexcept
   </code>
   (as of C++20), so
   <code>
    std::move_if_noexcept
   </code>
   returns
   <code>
    my_pair
   </code>
   as an l-value reference.  This causes
   <code>
    moved_pair
   </code>
   to be created via the copy constructor (rather than the move constructor).  The copy constructor can throw safely, because it doesn’t modify the source object.
  </p>
  <p>
   The standard library uses
   <code>
    std::move_if_noexcept
   </code>
   often to optimize for functions that are
   <code>
    noexcept
   </code>
   .  For example,
   <code>
    std::vector::resize
   </code>
   will use move semantics if the element type has a
   <code>
    noexcept
   </code>
   move constructor, and copy semantics otherwise.  This means
   <code>
    std::vector
   </code>
   will generally operate faster with objects that have a
   <code>
    noexcept
   </code>
   move constructor.
  </p>
  <div class="cpp-note cpp-lightredbackground">
   <p class="cpp-note-title cpp-bottomline">
    Warning
   </p>
   <p>
    If a type has both potentially throwing move semantics and deleted copy semantics (the copy constructor and copy assignment operator are unavailable), then
    <code>
     std::move_if_noexcept
    </code>
    will waive the strong guarantee and invoke move semantics. This conditional waiving of the strong guarantee is ubiquitous in the standard library container classes, since they use std::move_if_noexcept often.
   </p>
  </div>
  <!-- AI CONTENT END 1 -->
 </div>
 <!-- .entry-content -->
 <!-- .entry-utility -->
</div>
